1) need for rails active_support 2) softlayer seems to reboot their newly minted vm's, so put in a sleep to wait it out 3) always close popen fd's 4) fix a problem with server list/delete showing multiple copies of the same vm 5) be more precise about what conntest expects to see back 6) gin up a default perfrun for perfruns

diff --git a/BurUnixBench/RunRemote b/BurUnixBench/RunRemote
--- a/BurUnixBench/RunRemote
+++ b/BurUnixBench/RunRemote
@@ -87,6 +87,7 @@ else
     ssh $SSHOPTS $PORT $SSH_HOST $CMD 
 fi
 if [ $? != 0 ]; then
-    echo "RunRemote failed for: $@"
+    echo "RunRemote failed for: $@ ${INSTANCE}"
+    exit 1
 fi
 exit 0
