1) add https to list of protocols to proxy for Run 2) fix login_as 3) fix wget through proxies 4) give better diagnostics when tarball fetch fails

diff --git a/BurUnixBench/RunRemote b/BurUnixBench/RunRemote
--- a/BurUnixBench/RunRemote
+++ b/BurUnixBench/RunRemote
@@ -43,7 +43,7 @@ do
 	;;
     -x|--proxy-url)
 	PROXY="-x $2"
-        WGET_PROXY="http_proxy='$2' https_proxy='$2'"
+        WGET_PROXY="export http_proxy='$2'; export https_proxy='$2';"
 	shift
 	;;
     -H|--app-host)
@@ -81,7 +81,7 @@ if [ "$APP_KEY" != "" -a "$APP_SECRET" != "" ]; then
 fi
 #DOWNLOAD_HOST=$APP_HOST
 DOWNLOAD_HOST=staging.burstorm.com
-CMD="TAR=\"${DISTO}-\`uname -m\`-\`uname\`.tgz\"; rm -rf \${TAR} ${DISTO}; which wget > /dev/null; wgs=\$?; which curl > /dev/null; cls=\$?; if [ \"\$cls\" = '0' ]; then curl -o \${TAR} ${PROXY} https://${DOWNLOAD_HOST}/bench-disto/\${TAR}; elif [ \"\$wgs\" = '0' ]; then $WGET_PROXY wget -q -O \${TAR} https://${DOWNLOAD_HOST}/bench-disto/\${TAR}; else echo 'neither curl or wget are installed. giving up.'; exit 1; fi; tar xzf \${TAR}; cd ${DISTO}; ./ub -i 1 $APP -I '$INSTANCE' -O '$OBJECTIVE' $PROXY $CREATE_TIME"
+CMD="TAR=\"${DISTO}-\`uname -m\`-\`uname\`.tgz\"; rm -rf \${TAR} ${DISTO}; which wget > /dev/null; wgs=\$?; which curl > /dev/null; cls=\$?; if [ \"\$cls\" = '0' ]; then curl -o \${TAR} ${PROXY} https://${DOWNLOAD_HOST}/bench-disto/\${TAR}; getsts=\$?; elif [ \"\$wgs\" = '0' ]; then $WGET_PROXY wget -q -O \${TAR} https://${DOWNLOAD_HOST}/bench-disto/\${TAR}; getsts=\$?; else echo 'neither curl or wget are installed. giving up.'; exit 1; fi; if [ \$getsts -ne 0 ]; then echo 'Download of BurUnixBench failed. proxy settings?'; exit 1; fi; tar xzf \${TAR} 2>/dev/null; cd ${DISTO}; ./ub -i 1 $APP -I '$INSTANCE' -O '$OBJECTIVE' $PROXY $CREATE_TIME"
 # execute locally
 SSHOPTS="-o LogLevel=quiet -oStrictHostKeyChecking=no -oBatchMode=yes"
 if [ "$SSH_HOST" = "" ]; then
